### ISSUE TITLE
weird error, stack trace from @reach/router [Question]

### ISSUE THREAD

**Issue by llaenowyd** [salvoravida/redux-first-history#39]
I added @reach/router 1.3.4 and redux-first-history to a functional React app.

Now when I try dispatching a `push` action, I get the following stack

```
Uncaught TypeError: Cannot read property 'split' of undefined
    at pick (main.bundle.js:13228)
    at RouterImpl.render (main.bundle.js:12482)
    at finishClassComponent (main.bundle.js:59847)
    at updateClassComponent (main.bundle.js:59797)
    at beginWork (main.bundle.js:61435)
    at HTMLUnknownElement.callCallback (main.bundle.js:46307)
    at Object.invokeGuardedCallbackDev (main.bundle.js:46356)
    at invokeGuardedCallback (main.bundle.js:46418)
    at beginWork$1 (main.bundle.js:66321)
    at performUnitOfWork (main.bundle.js:65133)
```

The first frame `pick` is at [@reach/router/lib/utils.js:34](https://github.com/reach/router/blob/e203fe612236851a0bd3c77dba693e539a351c62/src/lib/utils.js#L34)

I went into `node_modules/@reach/router/es/lib/utils.js` and put a `console.log` in front of that line and `uri` is `undefined`.

This is porting a working router solution to a new app, so perhaps the new app build settings or other libs are contributing, or I forgot some detail putting it altogether.

Redux looks fine before and after the `push` action, after the push action the `router/location` part of the store looks correctly updated.  Along with the stack trace I get a kind of stack of React components,

```
  at RouterImpl (eval at ES6ProxyComponentFactory (http://localhost:3000/main.bundle.js:1:1), <anonymous>:14:7)
    at Location (http://localhost:3000/main.bundle.js:69504:20)
    at Router
    at LocationProvider (eval at ES6ProxyComponentFactory (http://localhost:3000/main.bundle.js:1:1), <anonymous>:14:7)
    at AppRouter (http://localhost:3000/main.bundle.js:69504:20)
    at div
    at Paper (http://localhost:3000/main.bundle.js:5426:23)
    at WithStyles(ForwardRef(Paper)) (http://localhost:3000/main.bundle.js:11454:31)
    at div
    at Container (http://localhost:3000/main.bundle.js:1723:23)
    at WithStyles(ForwardRef(Container)) (http://localhost:3000/main.bundle.js:11454:31)
    at div
    at ThemedAppContent (http://localhost:3000/main.bundle.js:69504:20)
    at ThemeProvider (http://localhost:3000/main.bundle.js:69504:20)
    at ThemeProvider (http://localhost:3000/main.bundle.js:69504:20)
    at Provider (http://localhost:3000/main.bundle.js:69504:20)
    at Provider (http://localhost:3000/main.bundle.js:69504:20)
```

I'm not sure what I might try to debug it, maybe willing to try a different routing lib instead of @reach

**Comment by salvoravida** [comment]
do you have a code sand box with code example?
