### ISSUE TITLE
SyntaxError when importing /rr6 (Cannot use import statement outside a module)

### ISSUE THREAD

**Issue by flying-sheep** [salvoravida/redux-first-history#59]
The following code breaks when running my jest test suite:

```js
import { Router } from 'redux-first-history/rr6'
```

```
    .../node_modules/redux-first-history/rr6/index.js:2
    import React from 'react';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      4 | import { History } from 'history'
      5 | import { FC } from 'react'
    > 6 | import { HistoryRouter as Router } from 'redux-first-history/rr6'
        | ^
      7 |
      8 | import AppWithRouterAccess from './AppWithRouterAccess'
      9 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/App.tsx:6:1)
```

I guess adding a `package.json` with the content

```json
{"type": "module"}
```

to the `rr6` folder should fix this.

**Comment by salvoravida** [comment]
flying-sheep: try 5.0.5 https://github.com/salvoravida/redux-first-history/releases/tag/v5.0.5
